#!/bin/bash

case $1 in
backup)
        comm -23 <(pacman -Qeq|sort) <(pacman -Qmq|sort) > /home/adam/scripts/pkglist.txt
        ;;
restore)
        sudo pacman -S $(< /home/adam/scripts/pkglist.txt)
        ;;
install)
        sudo pacman -S $2 $3 $4 $5 $6 $7 $8 $9
        ;;
remove)
        sudo pacman -Rs $2 $3 $4 $5 $6 $7 $8 $9
        ;;
search)
        pacman -Ss $2 $3 $4 $5 $6 $7 $8 $9
esac
