#!/bin/bash
case $1 in
    my)
        export REPO=AdamClements
        shift
        ;;
    *)
        export REPO=TouchType
        ;;
esac

case $1 in
    fork)
        export FORK=TouchType
        shift
        ;;
    *)
        unset $FORK
        ;;
esac

case $1 in
    branching)
        export BRANCHING=true
        shift
        ;;
    *)
        unset $BRANCHING
        ;;
esac        
    

PROJECT=$1
shift

FOLDER=${1:-$PROJECT}
shift

git clone git@github.com:$REPO/$PROJECT.git $FOLDER
cd $FOLDER

if [[ $FORK ]]
then
    git remote add upstream git@github.com:$FORK/$PROJECT.git
    git fetch upstream
fi

if [[ $BRANCHING ]]
then
    git checkout -b $FOLDER
    git pull upstream master
fi
