#!/bin/bash
case $1 in
my)
        export REPO=AdamClements
        shift
        ;;
*)
        export REPO=TouchType
        ;;
esac

PROJECT=$1
shift

git clone git@github.com:$REPO/$PROJECT.git "$@"
